service: superduperbot # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-central-1

functions:
  sendMessage:
    handler: handler.sendMessage
    events:
      - http: POST sendMessage